/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Admin.employees.RoundedPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author abdullah
 */
public class employees extends javax.swing.JFrame {

    /**
     * Creates new form employees
     */
    public employees() {
        initComponents();
         orders_available();
        pn_employee_op.setVisible(false);
       pending_order();
  
        
    }
    public void user_select(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
           Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/xz_shopping_center","root","Yossf#443");
             String sqluser="select * from trackdb where order_id='"+order_id.getText()+"'";
              PreparedStatement pst;
              pst=conn.prepareStatement(sqluser);
           ResultSet rs1 = pst.executeQuery();
            if (rs1.next()) {
                String user_idd= rs1.getString("User_id");
                 user_id_op.setText(user_idd);  
            }
         
        } catch (Exception e) {
        }
        
    }
    
    
    
    
     public void pending_order(){ 
              
             
          try {
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/xz_shopping_center","root","Yossf#443");
           String sql="select taking_order_id,name,Order_details, address, order_total,payment_method,date,order_state  from taking_order where emp_id='"+emp_id.getText()+"'  ";
 
           PreparedStatement ps ;
           ps=conn.prepareStatement(sql);
           ResultSet rs =ps.executeQuery();
           Table_track.setModel(DbUtils.resultSetToTableModel(rs)); 
           
          } catch (Exception e) { 
              JOptionPane.showMessageDialog(null, e);
          }
      }
     
     
     
      public void orders_available(){ 
              
             
          try {
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/xz_shopping_center","root","Yossf#443");
           String sql="SELECT \n" +
"trackdb.order_id,\n" +
"register.name,\n" +
"trackdb.Order_details,\n" +
"trackdb.adress,\n" +
"trackdb.order_total,\n" +
"trackdb.payment_method,"+
"trackdb.date\n" +
"from register\n" +
"inner join trackdb\n" +
"ON register.register_id=trackdb.user_id ";
           PreparedStatement ps ;
           ps=conn.prepareStatement(sql);
           ResultSet rs =ps.executeQuery();
           orders_available.setModel(DbUtils.resultSetToTableModel(rs)); 
           
          } catch (Exception e) { 
              JOptionPane.showMessageDialog(null, e);
          }
      }
          
     public void search_in_orders(){
     try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/xz_shopping_center","root","Yossf#443");
            String sql = "select taking_order_id,name,Order_details, address, order_total,payment_method,date,order_state  from taking_order  where taking_order_id='"+ order_search.getText()+"' && emp_id='"+emp_id.getText()+"' ";
            PreparedStatement ps ;
            ps=conn.prepareStatement(sql);
            ResultSet rs= ps.executeQuery();
      
            if (rs.next()) {
                rs= ps.executeQuery();

                Table_track.setModel(DbUtils.resultSetToTableModel(rs));

            }else{

                JOptionPane.showMessageDialog(null, "Order ID not found");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }                                         


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel17 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Order_s = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jPanel4 = new RoundedPanel(120,new Color(255,204,102));
        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new RoundedPanel(120,new Color(255,204,102));
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel10 =  new RoundedPanel(120,new Color(255,204,102));
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel11 = new RoundedPanel(120,new Color(255,204,102));
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Orders = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Table_track = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        kGradientPanel16 = new keeptoo.KGradientPanel();
        updateProduct5 = new javax.swing.JButton();
        deleteProduct5 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        bill_text_area1 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox<>();
        lbl_Order_Id1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        bill_amount1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        order_search1 = new javax.swing.JTextField();
        kGradientPanel17 = new keeptoo.KGradientPanel();
        updateProduct6 = new javax.swing.JButton();
        deleteProduct6 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        bill_text_area2 = new javax.swing.JTextArea();
        jComboBox3 = new javax.swing.JComboBox<>();
        lbl_Order_Id = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        bill_amount = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        order_search = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        txt_area_address = new javax.swing.JTextArea();
        Complated_order = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Taking_order_pn = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orders_available = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        order_id = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        order_data = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        total_amount = new javax.swing.JTextField();
        payment_method = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        details = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        pn_employee_op = new javax.swing.JPanel();
        Order_State_emp = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        emp_id = new javax.swing.JTextField();
        user_id_op = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        kGradientPanel3.setBackground(new java.awt.Color(204, 255, 204));
        kGradientPanel3.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel3.setkGradientFocus(1200);
        kGradientPanel3.setkStartColor(new java.awt.Color(0, 0, 0));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\resize\\127412176-x-z-x-z-logo-initial-vector-mark-initial-letter-x-z-x-z-luxury-art-vector-mark-logo-rose-gold-silver-removebg-preview.png")); // NOI18N
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel10.setFont(new java.awt.Font("Javanese Text", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Shopping Center");

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(Home, "card6");

        Order_s.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setBackground(new java.awt.Color(102, 0, 0));
        kGradientPanel2.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnterd(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mousePress(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/order pending.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Batang", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(60, 60, 60));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Pending Orders");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        kGradientPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 439, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnterd(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mousePress(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/complate order (2).png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Batang", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(60, 60, 60));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Complated Orders");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        kGradientPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 439, -1, -1));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10mouseEnterd(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10mouseExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mousePress(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dtails.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Batang", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("My Details");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
        );

        kGradientPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 57, -1, -1));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel11mouseEnterd(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel11mouseExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mousePress(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deliveryed (1).png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Batang", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(60, 60, 60));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Taking More Orders");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
        );

        kGradientPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 57, -1, -1));

        Order_s.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 750));

        jPanel1.add(Order_s, "card2");

        Orders.setBackground(new java.awt.Color(0, 0, 0));

        Table_track.setAutoCreateRowSorter(true);
        Table_track.setBackground(new java.awt.Color(255, 204, 102));
        Table_track.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Table_track.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        Table_track.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_track.setToolTipText("");
        Table_track.setGridColor(new java.awt.Color(255, 51, 0));
        Table_track.setRequestFocusEnabled(false);
        Table_track.setRowHeight(35);
        Table_track.setSelectionBackground(new java.awt.Color(204, 204, 0));
        Table_track.setSelectionForeground(new java.awt.Color(255, 0, 0));
        Table_track.setShowGrid(true);
        Table_track.setSurrendersFocusOnKeystroke(true);
        Table_track.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_trackMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(Table_track);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel16.setkEndColor(new java.awt.Color(255, 153, 51));
        kGradientPanel16.setkStartColor(new java.awt.Color(255, 153, 51));
        kGradientPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateProduct5.setBackground(new java.awt.Color(51, 0, 51));
        updateProduct5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        updateProduct5.setText("Update");
        updateProduct5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        updateProduct5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProduct5ActionPerformed(evt);
            }
        });
        kGradientPanel16.add(updateProduct5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 694, 124, 45));

        deleteProduct5.setBackground(new java.awt.Color(51, 0, 51));
        deleteProduct5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        deleteProduct5.setText("Delete");
        deleteProduct5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteProduct5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProduct5ActionPerformed(evt);
            }
        });
        kGradientPanel16.add(deleteProduct5, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 694, 122, 45));

        jButton16.setBackground(new java.awt.Color(51, 0, 51));
        jButton16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton16.setText("Print");
        jButton16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        kGradientPanel16.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 694, 130, 45));

        bill_text_area1.setColumns(20);
        bill_text_area1.setRows(5);
        jScrollPane8.setViewportView(bill_text_area1);

        kGradientPanel16.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 424, 244));

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "IN Transit", "Reached Destinition", "Out for Delivery", "Complated" }));
        kGradientPanel16.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 424, 46));

        lbl_Order_Id1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Order_Id1.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        lbl_Order_Id1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Order_Id1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kGradientPanel16.add(lbl_Order_Id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 286, 91, 60));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Order Id :");
        kGradientPanel16.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 286, 96, 60));

        jLabel19.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Total amount ");
        kGradientPanel16.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 286, 102, 60));

        bill_amount1.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        bill_amount1.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel16.add(bill_amount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 286, 113, 60));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Search_25px_2.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        kGradientPanel16.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 39, 35));

        order_search1.setBackground(new java.awt.Color(0, 0, 0));
        order_search1.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        order_search1.setForeground(new java.awt.Color(204, 204, 204));
        order_search1.setText("Search by Order ID");
        order_search1.setBorder(null);
        order_search1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                order_search1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                order_search1FocusLost(evt);
            }
        });
        order_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_search1ActionPerformed(evt);
            }
        });
        order_search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                order_search1KeyPressed(evt);
            }
        });
        kGradientPanel16.add(order_search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 11, 258, 35));

        jPanel7.add(kGradientPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        kGradientPanel17.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel17.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateProduct6.setBackground(new java.awt.Color(51, 0, 51));
        updateProduct6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        updateProduct6.setText("Update");
        updateProduct6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        updateProduct6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProduct6ActionPerformed(evt);
            }
        });
        kGradientPanel17.add(updateProduct6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 694, 120, 45));

        deleteProduct6.setBackground(new java.awt.Color(51, 0, 51));
        deleteProduct6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        deleteProduct6.setText("Delete");
        deleteProduct6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteProduct6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProduct6ActionPerformed(evt);
            }
        });
        kGradientPanel17.add(deleteProduct6, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 694, 110, 45));

        jButton17.setBackground(new java.awt.Color(51, 0, 51));
        jButton17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton17.setText("Print");
        jButton17.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        kGradientPanel17.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 694, 110, 45));

        bill_text_area2.setBackground(new java.awt.Color(0, 0, 0));
        bill_text_area2.setColumns(20);
        bill_text_area2.setForeground(new java.awt.Color(255, 255, 255));
        bill_text_area2.setRows(5);
        jScrollPane9.setViewportView(bill_text_area2);

        kGradientPanel17.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 400, 244));

        jComboBox3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "IN Transit", "Reached Destinition", "Out for Delivery", "Complated" }));
        kGradientPanel17.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 400, 46));

        lbl_Order_Id.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Order_Id.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        lbl_Order_Id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Order_Id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kGradientPanel17.add(lbl_Order_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 150, 70, 60));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Order Id :");
        kGradientPanel17.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 150, 90, 60));

        jLabel40.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Total amount ");
        kGradientPanel17.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 150, 110, 60));

        bill_amount.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        bill_amount.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel17.add(bill_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 100, 60));

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Search_25px_2.png"))); // NOI18N
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        kGradientPanel17.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 39, 35));

        order_search.setBackground(new java.awt.Color(0, 0, 0));
        order_search.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        order_search.setForeground(new java.awt.Color(204, 204, 204));
        order_search.setText("Search by Order ID");
        order_search.setBorder(null);
        order_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                order_searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                order_searchFocusLost(evt);
            }
        });
        order_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_searchActionPerformed(evt);
            }
        });
        order_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                order_searchKeyPressed(evt);
            }
        });
        kGradientPanel17.add(order_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 11, 248, 35));

        txt_area_address.setBackground(new java.awt.Color(0, 0, 0));
        txt_area_address.setColumns(20);
        txt_area_address.setForeground(new java.awt.Color(255, 255, 255));
        txt_area_address.setRows(5);
        jScrollPane10.setViewportView(txt_area_address);

        kGradientPanel17.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 400, 120));

        jPanel7.add(kGradientPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 750));

        javax.swing.GroupLayout OrdersLayout = new javax.swing.GroupLayout(Orders);
        Orders.setLayout(OrdersLayout);
        OrdersLayout.setHorizontalGroup(
            OrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrdersLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        OrdersLayout.setVerticalGroup(
            OrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane6)
        );

        jPanel1.add(Orders, "card3");

        jTable1.setBackground(new java.awt.Color(255, 204, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(32);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout Complated_orderLayout = new javax.swing.GroupLayout(Complated_order);
        Complated_order.setLayout(Complated_orderLayout);
        Complated_orderLayout.setHorizontalGroup(
            Complated_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        Complated_orderLayout.setVerticalGroup(
            Complated_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        jPanel1.add(Complated_order, "card4");

        Taking_order_pn.setBackground(new java.awt.Color(255, 153, 102));
        Taking_order_pn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(186, 186, 186))
        );

        kGradientPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 750));

        orders_available.setBackground(new java.awt.Color(255, 204, 102));
        orders_available.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        orders_available.setRowHeight(32);
        orders_available.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orders_availableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(orders_available);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 440, 750));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Address");
        kGradientPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 120, 140));

        order_id.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        order_id.setForeground(new java.awt.Color(51, 51, 51));
        order_id.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                order_idCaretUpdate(evt);
            }
        });
        kGradientPanel1.add(order_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 290, 40));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("ID");
        kGradientPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 40));

        Name.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(51, 51, 51));
        kGradientPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 290, 40));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Name");
        kGradientPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, 40));

        order_data.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        order_data.setForeground(new java.awt.Color(51, 51, 51));
        kGradientPanel1.add(order_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, 290, 40));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Date");
        kGradientPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 120, 40));

        address.setColumns(20);
        address.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        address.setLineWrap(true);
        address.setRows(5);
        address.setWrapStyleWord(true);
        jScrollPane3.setViewportView(address);

        kGradientPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 290, 140));

        jButton3.setBackground(new java.awt.Color(0, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton3.setText("Add");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 420, 50));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Total");
        kGradientPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 120, 40));

        total_amount.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        total_amount.setForeground(new java.awt.Color(51, 51, 51));
        kGradientPanel1.add(total_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 290, 40));

        payment_method.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        payment_method.setForeground(new java.awt.Color(51, 51, 51));
        kGradientPanel1.add(payment_method, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 290, 40));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Payment ");
        kGradientPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 120, 40));

        details.setBackground(new java.awt.Color(0, 0, 0));
        details.setColumns(20);
        details.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        details.setForeground(new java.awt.Color(255, 255, 255));
        details.setRows(5);
        jScrollPane4.setViewportView(details);

        kGradientPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 290, 160));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Order Details");
        kGradientPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 160));

        pn_employee_op.setBackground(new java.awt.Color(255, 204, 51));

        Order_State_emp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Order_State_emp.setText("Pending");
        Order_State_emp.setEnabled(false);
        Order_State_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Order_State_empActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel36.setText("Order_State");

        jLabel37.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel37.setText("Employee_id");

        emp_id.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        emp_id.setText("2");
        emp_id.setEnabled(false);
        emp_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_idActionPerformed(evt);
            }
        });

        user_id_op.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        user_id_op.setEnabled(false);
        user_id_op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_id_opActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel38.setText("Employee_id");

        javax.swing.GroupLayout pn_employee_opLayout = new javax.swing.GroupLayout(pn_employee_op);
        pn_employee_op.setLayout(pn_employee_opLayout);
        pn_employee_opLayout.setHorizontalGroup(
            pn_employee_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_employee_opLayout.createSequentialGroup()
                .addGroup(pn_employee_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_employee_opLayout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Order_State_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_employee_opLayout.createSequentialGroup()
                        .addGroup(pn_employee_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pn_employee_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(user_id_op)
                            .addComponent(emp_id, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_employee_opLayout.setVerticalGroup(
            pn_employee_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_employee_opLayout.createSequentialGroup()
                .addGroup(pn_employee_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Order_State_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_employee_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_employee_opLayout.createSequentialGroup()
                        .addComponent(emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_employee_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user_id_op, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel1.add(pn_employee_op, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 400, 0));

        Taking_order_pn.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 750));

        jPanel1.add(Taking_order_pn, "card5");

        jPanel17.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 880, 750));

        jPanel16.setBackground(new java.awt.Color(0, 0, 0));

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mousePress(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Home");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel14.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mousePress(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Orders");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel14.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 200, -1));

        jLabel11.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("   Logout");
        jPanel14.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 739, 180, 0));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mouseEnterd(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnterd
    
      
           
    }//GEN-LAST:event_mouseEnterd

    private void mouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExit
     
               
    }//GEN-LAST:event_mouseExit

    private void Table_trackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_trackMouseClicked
        int row=Table_track.getSelectedRow();
        bill_text_area2.setText(Table_track.getValueAt(row, 2).toString());
        lbl_Order_Id.setText(Table_track.getValueAt(row, 0).toString());
        jComboBox3.setSelectedItem(Table_track.getValueAt(row, 7).toString());
        bill_amount.setText(Table_track.getValueAt(row, 4).toString());
        txt_area_address.setText(Table_track.getValueAt(row, 3).toString());
    }//GEN-LAST:event_Table_trackMouseClicked

    private void mousePress(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousePress
       if (evt.getSource() == jPanel4) {
              Order_s.setVisible(false);
              Orders.setVisible(true);
              Taking_order_pn.setVisible(false);
              Home.setVisible(false);
              Complated_order.setVisible(false);
              
        }
          if (evt.getSource() == jPanel11) {
              Order_s.setVisible(false);
              Orders.setVisible(false);
              Taking_order_pn.setVisible(true);
              Home.setVisible(false);
                 Complated_order.setVisible(false);
        }
          if (evt.getSource() == jPanel8) {
              Order_s.setVisible(false);
              Orders.setVisible(false);
              Taking_order_pn.setVisible(false);
              Home.setVisible(true);
                 Complated_order.setVisible(false);
        }
          if (evt.getSource() == jPanel9) {
              Order_s.setVisible(true);
              Orders.setVisible(false);
              Taking_order_pn.setVisible(false);
              Home.setVisible(false);
              Complated_order.setVisible(false);
        }
           if (evt.getSource() == jPanel5) {
              Order_s.setVisible(false);
              Orders.setVisible(false);
              Taking_order_pn.setVisible(false);
              Home.setVisible(false);
              Complated_order.setVisible(true);
        }
         
         
         
         
    }//GEN-LAST:event_mousePress

    private void orders_availableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orders_availableMouseClicked
      int row =orders_available.getSelectedRow();
      order_id.setText(orders_available.getValueAt(row, 0).toString());
      Name.setText(orders_available.getValueAt(row, 1).toString());
      details.setText(orders_available.getValueAt(row, 2).toString());
      address.setText(orders_available.getValueAt(row, 3).toString());
      total_amount.setText(orders_available.getValueAt(row,4).toString());
      payment_method.setText(orders_available.getValueAt(row, 5).toString());
      order_data.setText(orders_available.getValueAt(row, 6).toString());
    
                         
    }//GEN-LAST:event_orders_availableMouseClicked

    private void Order_State_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Order_State_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Order_State_empActionPerformed

    private void emp_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_idActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  int s= JOptionPane.showConfirmDialog(null, "<html><font size=5 bold  color=black>Are you sure ?</font><p><p><font size=3 bold color=red>Note:</font><font size=3 color=black>If you take the item then you can not cancel it later !!! </font></html>","CONFIRM",JOptionPane.YES_NO_OPTION);
       
         if (s==0  ) {
            
            
            try {
      //insert
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/xz_shopping_center","root","Yossf#443");
           String sql = "insert into taking_order values(?,?,?,?,?,?,?,?,?,?) ";          
           java.util.Date date=new java.util.Date();
	   java.sql.Timestamp sqlTime=new java.sql.Timestamp(date.getTime());
           PreparedStatement ps ;
         ps=conn.prepareStatement(sql);
         ps.setString(1, emp_id.getText());
         ps.setString(2, order_id.getText());
         ps.setString(3, user_id_op.getText());
         ps.setString(4, Name.getText());
         ps.setString(5, details.getText());
         ps.setString(6, address.getText());
         ps.setString(7,total_amount.getText());
         ps.setString(8, payment_method.getText());
         ps.setTimestamp(9, sqlTime);
         ps.setString(10, Order_State_emp.getText());
        
          ps.executeUpdate();
          JOptionPane.showMessageDialog(null, "Your order is placed");
          
      // delete 
          String del_sql = "Delete from trackdb  where order_id ='"+order_id.getText()+"' ";
          PreparedStatement ps1 ;
          ps1=conn.prepareStatement(del_sql);
          ps1.executeUpdate();
          JOptionPane.showMessageDialog(null, "Your order is del");
          orders_available();
          
           
             }catch(Exception e){
                  JOptionPane.showMessageDialog(null, e);
            } 
            
  }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void user_id_opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_id_opActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_id_opActionPerformed

    private void order_idCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_order_idCaretUpdate
user_select();
    }//GEN-LAST:event_order_idCaretUpdate

    private void jPanel10mouseEnterd(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10mouseEnterd

    }//GEN-LAST:event_jPanel10mouseEnterd

    private void jPanel10mouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10mouseExit

    }//GEN-LAST:event_jPanel10mouseExit

    private void jPanel11mouseEnterd(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11mouseEnterd

    }//GEN-LAST:event_jPanel11mouseEnterd

    private void jPanel11mouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11mouseExit

    }//GEN-LAST:event_jPanel11mouseExit

    private void updateProduct5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProduct5ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/xz_shopping_center","root","Yossf#443");
            String sql = "update  taking_order set order_state=? where taking_order_id ='"+lbl_Order_Id.getText()+"' ";
            PreparedStatement ps ;
            ps=conn.prepareStatement(sql);

            ps.setString(1, jComboBox3.getSelectedItem().toString());
            ps.executeUpdate();

            pending_order();
            JOptionPane.showMessageDialog(null, "secuss");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateProduct5ActionPerformed

    private void deleteProduct5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProduct5ActionPerformed
        int s= JOptionPane.showConfirmDialog(null, "Do you want to Delete","Delete",JOptionPane.YES_NO_OPTION);
        if (s==0) {

            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/xz_shopping_center","root","Yossf#443");
                String sql = "delete from  taking_order where taking_order_id =?";
                PreparedStatement ps ;
                ps=conn.prepareStatement(sql);
                ps.setString(1,lbl_Order_Id.getText());
                ps.executeUpdate();

                pending_order();
                JOptionPane.showMessageDialog(null, "secuss");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_deleteProduct5ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        search_in_orders();
    }//GEN-LAST:event_jLabel23MouseClicked

    private void order_search1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_order_search1FocusGained
        order_search.setText("");
    }//GEN-LAST:event_order_search1FocusGained

    private void order_search1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_order_search1FocusLost
        order_search.setText("Search by Order ID");
    }//GEN-LAST:event_order_search1FocusLost

    private void order_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_order_search1ActionPerformed

    private void order_search1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_order_search1KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (order_search.getText().isEmpty()) {
                pending_order();
            }else{
                search_in_orders();
            }
        }
    }//GEN-LAST:event_order_search1KeyPressed

    private void updateProduct6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProduct6ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/xz_shopping_center","root","Yossf#443");
            String sql = "update  taking_order set order_state=? where taking_order_id ='"+lbl_Order_Id.getText()+"' ";
            PreparedStatement ps ;
            ps=conn.prepareStatement(sql);

            ps.setString(1, jComboBox3.getSelectedItem().toString());
            ps.executeUpdate();

            pending_order();
            JOptionPane.showMessageDialog(null, "secuss");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateProduct6ActionPerformed

    private void deleteProduct6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProduct6ActionPerformed
        int s= JOptionPane.showConfirmDialog(null, "Do you want to Delete","Delete",JOptionPane.YES_NO_OPTION);
        if (s==0) {

            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/xz_shopping_center","root","Yossf#443");
                String sql = "delete from  taking_order where taking_order_id =?";
                PreparedStatement ps ;
                ps=conn.prepareStatement(sql);
                ps.setString(1,lbl_Order_Id.getText());
                ps.executeUpdate();

                pending_order();
                JOptionPane.showMessageDialog(null, "secuss");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_deleteProduct6ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

    }//GEN-LAST:event_jButton17ActionPerformed

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        search_in_orders();
    }//GEN-LAST:event_jLabel41MouseClicked

    private void order_searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_order_searchFocusGained
        order_search.setText("");
    }//GEN-LAST:event_order_searchFocusGained

    private void order_searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_order_searchFocusLost
        order_search.setText("Search by Order ID");
    }//GEN-LAST:event_order_searchFocusLost

    private void order_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_order_searchActionPerformed

    private void order_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_order_searchKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (order_search.getText().isEmpty()) {
                pending_order();
            }else{
                search_in_orders();
            }
        }
    }//GEN-LAST:event_order_searchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Complated_order;
    private javax.swing.JPanel Home;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Order_State_emp;
    private javax.swing.JPanel Order_s;
    private javax.swing.JPanel Orders;
    private javax.swing.JTable Table_track;
    private javax.swing.JPanel Taking_order_pn;
    private javax.swing.JTextArea address;
    private javax.swing.JLabel bill_amount;
    private javax.swing.JLabel bill_amount1;
    private javax.swing.JTextArea bill_text_area1;
    private javax.swing.JTextArea bill_text_area2;
    private javax.swing.JButton deleteProduct5;
    private javax.swing.JButton deleteProduct6;
    private javax.swing.JTextArea details;
    public static javax.swing.JTextField emp_id;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel16;
    private keeptoo.KGradientPanel kGradientPanel17;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel lbl_Order_Id;
    private javax.swing.JLabel lbl_Order_Id1;
    private javax.swing.JTextField order_data;
    private javax.swing.JTextField order_id;
    private javax.swing.JTextField order_search;
    private javax.swing.JTextField order_search1;
    private javax.swing.JTable orders_available;
    private javax.swing.JTextField payment_method;
    private javax.swing.JPanel pn_employee_op;
    private javax.swing.JTextField total_amount;
    private javax.swing.JTextArea txt_area_address;
    private javax.swing.JButton updateProduct5;
    private javax.swing.JButton updateProduct6;
    public static javax.swing.JTextField user_id_op;
    // End of variables declaration//GEN-END:variables
class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;

        }

        public RoundedPanel(int radius, Color bgColor) {       //888888
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        private RoundedPanel(int i, int i0) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
            // graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border

        }
    }}
